# Generated by Django 2.1.11 on 2019-08-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minutoes',
            new_name='time_minutes',
        ),
    ]
